spring.application.name=userservice

# ===============================
# DATABASE CONFIG
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/fitness_user_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false

# ===============================
# HIKARI POOL
# ==============================
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.auto-commit=false

# ===============================
# EUREKA SERVER
# ==============================
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# ===============================
# LOGGING
# ==============================
#logging config file path (log4j2.xml)
logging.config=config/log4j2.xml

#log folder generation directory
log.dir=logs
