spring.application.name=activityservice


# ===============================
# LOGGING
# ==============================
#logging config file path (log4j2.xml)
logging.config=config/log4j2.xml

#log folder generation directory
log.dir=logs