spring.application.name=userservice

# ===============================
# DATABASE CONFIG
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/fitness_user_db
spring.datasource.username=postgres
spring.datasource.password=root@123
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true


# ===============================
# LOGGING
# ==============================
#logging config file path (log4j2.xml)
logging.config=config/log4j2.xml

#log folder generation directory
log.dir=logs
