spring.application.name=eureka
server.port=8761

# ===============================
# LOGGING
# ==============================
#logging config file path (log4j2.xml)
logging.config=config/log4j2.xml

#log folder generation directory
log.dir=logs


# ===============================
# MongoDB Configuration
# ===============================
spring.data.mongodb.uri=mongodb://localhost:27017/fitnessactivitydb




eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
